[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
pythonpath = ". src"
python_files = [
    "tests.py",
    "test_*.py",
    "*_tests.py"
]
testpaths = ["tests"]
